# Generated by Django 4.2.20 on 2025-06-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaoTri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_bao_tri", models.CharField(max_length=20, unique=True)),
                ("tieu_de", models.CharField(max_length=200)),
                (
                    "loai_bao_tri",
                    models.CharField(
                        choices=[
                            ("Vệ_sinh", "Vệ sinh"),
                            ("Sửa_chữa", "Sửa chữa"),
                            ("Kiểm_tra", "Kiểm tra"),
                            ("Thay_thế", "Thay thế"),
                            ("Bảo_dưỡng", "Bảo dưỡng"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "doi_tuong",
                    models.CharField(
                        choices=[
                            ("Khu_vực", "Khu vực"),
                            ("Vị_trí", "Vị trí"),
                            ("Thiết_bị", "Thiết bị"),
                            ("Hệ_thống", "Hệ thống"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "doi_tuong_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("mo_ta", models.TextField()),
                (
                    "muc_do_uu_tien",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("nguoi_tao", models.CharField(max_length=50)),
                ("nguoi_thuc_hien", models.JSONField(blank=True, null=True)),
                ("thoi_gian_bat_dau", models.DateTimeField(blank=True, null=True)),
                ("thoi_gian_ket_thuc", models.DateTimeField(blank=True, null=True)),
                ("thoi_gian_uoc_tinh", models.IntegerField(blank=True, null=True)),
                (
                    "chi_phi_uoc_tinh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "chi_phi_thuc_te",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Kế_hoạch", "Kế hoạch"),
                            ("Đang_thực_hiện", "Đang_thực_hiện"),
                            ("Hoàn_thành", "Hoàn thành"),
                            ("Tạm_dừng", "Tạm dừng"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Kế_hoạch",
                        max_length=14,
                    ),
                ),
                ("ket_qua", models.TextField(blank=True, null=True)),
                ("hinh_anh_truoc", models.JSONField(blank=True, null=True)),
                ("hinh_anh_sau", models.JSONField(blank=True, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bảo trì",
                "verbose_name_plural": "Bảo trì",
                "db_table": "bao_tri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KiemKe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_kiem_ke", models.CharField(max_length=20, unique=True)),
                (
                    "loai_kiem_ke",
                    models.CharField(
                        choices=[
                            ("Toàn bộ", "Toàn bộ"),
                            ("Theo khu vực", "Theo khu vực"),
                            ("Theo nhóm hàng", "Theo nhóm hàng"),
                            ("Đột xuất", "Đột xuất"),
                            ("Theo HSD", "Theo hạn sử dụng"),
                        ],
                        max_length=30,
                    ),
                ),
                ("pham_vi_kiem_ke", models.JSONField(blank=True, null=True)),
                ("nguoi_tao", models.CharField(max_length=50)),
                ("nguoi_phu_trach", models.JSONField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Chuẩn bị", "Chuẩn bị"),
                            ("Đang thực hiện", "Đang thực hiện"),
                            ("Hoàn thành", "Hoàn thành"),
                            ("Tạm dừng", "Tạm dừng"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Chuẩn_bị",
                        max_length=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kiểm kê",
                "verbose_name_plural": "Kiểm kê",
                "db_table": "kiem_ke",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TinhTrangHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loai_tinh_trang",
                    models.CharField(
                        choices=[
                            ("Bình_thường", "Bình thường"),
                            ("Sắp_hết_hạn", "Sắp hết hạn"),
                            ("Cần_kiểm_tra_CL", "Cần kiểm tra CL"),
                            ("Có_vấn_đề", "Có vấn đề"),
                            ("Ưu_tiên_xuất", "Ưu tiên xuất"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "muc_do",
                    models.CharField(
                        choices=[
                            ("Thấp", "Thấp"),
                            ("Vừa", "Vừa"),
                            ("Cao", "Cao"),
                            ("Khẩn_cấp", "Khẩn cấp"),
                        ],
                        default="Vừa",
                        max_length=8,
                    ),
                ),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("ngay_phat_hien", models.DateField()),
                ("ngay_xu_ly", models.DateField(blank=True, null=True)),
                (
                    "nguoi_phat_hien",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nguoi_xu_ly", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đang_xử_lý", "Đang xử lý"),
                            ("Hoàn_thành", "Hoàn thành"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Mới",
                        max_length=10,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.pallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tình trạng hàng",
                "verbose_name_plural": "Tình trạng hàng",
                "db_table": "tinh_trang_hang",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChiTietKiemKe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_thung_he_thong", models.IntegerField()),
                ("han_su_dung_he_thong", models.DateField(blank=True, null=True)),
                (
                    "trang_thai_he_thong",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đã_mở", "Đã mở"),
                            ("Trống", "Trống"),
                        ],
                        default="Mới",
                        max_length=10,
                    ),
                ),
                ("so_thung_thuc_te", models.IntegerField(blank=True, null=True)),
                ("han_su_dung_thuc_te", models.DateField(blank=True, null=True)),
                (
                    "trang_thai_thuc_te",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới"),
                            ("Đã mở", "Đã mở"),
                            ("Trống", "Trống"),
                        ],
                        default="Mới",
                        max_length=10,
                    ),
                ),
                (
                    "tinh_trang_chat_luong",
                    models.CharField(
                        choices=[
                            ("Tốt", "Tốt"),
                            ("Khá", "Khá"),
                            ("Trung bình", "Trung Bình"),
                            ("Kém", "Kém"),
                            ("Hỏng", "Hỏng"),
                        ],
                        default="Tốt",
                        max_length=10,
                    ),
                ),
                ("chenh_lech_so_luong", models.IntegerField(blank=True, null=True)),
                (
                    "nguoi_kiem_ke",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("thoi_gian_kiem_ke", models.DateField(blank=True, null=True)),
                ("hinh_anh", models.JSONField(blank=True, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                (
                    "da_xu_ly_chenh_lech",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.pallet",
                    ),
                ),
                (
                    "phien_kiem_ke",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.kiemke",
                    ),
                ),
                (
                    "san_pham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.sanpham",
                    ),
                ),
                (
                    "vi_tri_kho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.vitrikho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết kiểm kê",
                "verbose_name_plural": "Chi tiết kiểm kê",
                "db_table": "chi_tiet_kiem_ke",
                "ordering": ["-created_at"],
            },
        ),
    ]
