# Generated by Django 4.2.20 on 2025-06-27 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chitietkiemke",
            old_name="so_thung_he_thong",
            new_name="chenh_lech",
        ),
        migrations.RenameField(
            model_name="chitietkiemke",
            old_name="phien_kiem_ke",
            new_name="kiem_ke",
        ),
        migrations.RenameField(
            model_name="chitietkiemke",
            old_name="chenh_lech_so_luong",
            new_name="so_luong_thuc_te",
        ),
        migrations.RemoveField(
            model_name="chitietkiemke",
            name="da_xu_ly_chenh_lech",
        ),
        migrations.RemoveField(
            model_name="chitietkiemke",
            name="han_su_dung_he_thong",
        ),
        migrations.RemoveField(
            model_name="chitietkiemke",
            name="han_su_dung_thuc_te",
        ),
        migrations.RemoveField(
            model_name="chitietkiemke",
            name="san_pham",
        ),
        migrations.RemoveField(
            model_name="chitietkiemke",
            name="so_thung_thuc_te",
        ),
        migrations.RemoveField(
            model_name="chitietkiemke",
            name="tinh_trang_chat_luong",
        ),
        migrations.RemoveField(
            model_name="chitietkiemke",
            name="trang_thai_he_thong",
        ),
        migrations.RemoveField(
            model_name="chitietkiemke",
            name="trang_thai_thuc_te",
        ),
        migrations.RemoveField(
            model_name="chitietkiemke",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="chitietkiemke",
            name="vi_tri_kho",
        ),
        migrations.RemoveField(
            model_name="kiemke",
            name="nguoi_phu_trach",
        ),
        migrations.AddField(
            model_name="chitietkiemke",
            name="so_luong_he_thong",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chitietkiemke",
            name="trang_thai_hang",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="kiemke",
            name="danh_sach_nguoi_phu_trach",
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name="kiemke",
            name="ghi_chu",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="kiemke",
            name="ngay_kiem_ke",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="doi_tuong",
            field=models.CharField(
                choices=[
                    ("Khu_vực", "Khu vực"),
                    ("Vị_trí", "Vị trí"),
                    ("Thiết_bị", "Thiết bị"),
                    ("Hệ_thống", "Hệ thống"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="ghi_chu",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="hinh_anh_sau",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="hinh_anh_truoc",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="ket_qua",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="loai_bao_tri",
            field=models.CharField(
                choices=[
                    ("Vệ_sinh", "Vệ sinh"),
                    ("Sửa_chữa", "Sửa chữa"),
                    ("Kiểm_tra", "Kiểm tra"),
                    ("Thay_thế", "Thay thế"),
                    ("Bảo_dưỡng", "Bảo dưỡng"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="mo_ta",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="muc_do_uu_tien",
            field=models.CharField(
                choices=[
                    ("Thấp", "Thấp"),
                    ("Vừa", "Vừa"),
                    ("Cao", "Cao"),
                    ("Khẩn_cấp", "Khẩn cấp"),
                ],
                default="Vừa",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="nguoi_thuc_hien",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="chitietkiemke",
            name="ghi_chu",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="chitietkiemke",
            name="hinh_anh",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="chitietkiemke",
            name="nguoi_kiem_ke",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="chitietkiemke",
            name="thoi_gian_kiem_ke",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="kiemke",
            name="loai_kiem_ke",
            field=models.CharField(
                choices=[
                    ("Toàn_kho", "Toàn kho"),
                    ("Khu_vực", "Khu vực"),
                    ("Theo_nhóm", "Theo nhóm"),
                    ("Theo_hạn_sử_dụng", "Theo hạn sử dụng"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="kiemke",
            name="pham_vi_kiem_ke",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="kiemke",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("Chuẩn_bị", "Chuẩn bị"),
                    ("Đang_kiểm_kê", "Đang kiểm kê"),
                    ("Hoàn_thành", "Hoàn thành"),
                    ("Hủy", "Hủy"),
                ],
                default="Chuẩn_bị",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tinhtranghang",
            name="ghi_chu",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="tinhtranghang",
            name="loai_tinh_trang",
            field=models.CharField(
                choices=[
                    ("Bình_thường", "Bình thường"),
                    ("Sắp_hết_hạn", "Sắp hết hạn"),
                    ("Cần_kiểm_tra_CL", "Cần kiểm tra CL"),
                    ("Có_vấn_đề", "Có vấn đề"),
                    ("Ưu_tiên_xuất", "Ưu tiên xuất"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tinhtranghang",
            name="mo_ta",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="tinhtranghang",
            name="muc_do",
            field=models.CharField(
                choices=[
                    ("Thấp", "Thấp"),
                    ("Vừa", "Vừa"),
                    ("Cao", "Cao"),
                    ("Khẩn_cấp", "Khẩn cấp"),
                ],
                default="Vừa",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tinhtranghang",
            name="nguoi_phat_hien",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="tinhtranghang",
            name="nguoi_xu_ly",
            field=models.CharField(default="", max_length=50),
        ),
    ]
