# Generated by Django 4.2.20 on 2025-06-29 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_rename_so_thung_he_thong_chitietkiemke_chenh_lech_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="baotri",
            name="chi_phi_thuc_te",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="chi_phi_uoc_tinh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="ghi_chu",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="thoi_gian_uoc_tinh",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="kiemke",
            name="ghi_chu",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="tinhtranghang",
            name="ghi_chu",
            field=models.TextField(blank=True, default=""),
        ),
    ]
