# Generated by Django 4.2.20 on 2025-07-01 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_baotri_chi_phi_thuc_te_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baotri",
            name="hinh_anh_sau",
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="hinh_anh_truoc",
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="mo_ta",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="baotri",
            name="nguoi_thuc_hien",
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name="chitietkiemke",
            name="chenh_lech",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="chitietkiemke",
            name="ghi_chu",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="chitietkiemke",
            name="hinh_anh",
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name="chitietkiemke",
            name="nguoi_kiem_ke",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="chitietkiemke",
            name="so_luong_he_thong",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="chitietkiemke",
            name="thoi_gian_kiem_ke",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="chitietkiemke",
            name="trang_thai_hang",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="kiemke",
            name="danh_sach_nguoi_phu_trach",
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name="kiemke",
            name="ngay_kiem_ke",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="kiemke",
            name="nguoi_tao",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="kiemke",
            name="pham_vi_kiem_ke",
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name="tinhtranghang",
            name="mo_ta",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="tinhtranghang",
            name="nguoi_phat_hien",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="tinhtranghang",
            name="nguoi_xu_ly",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
