# Generated by Django 4.2.20 on 2025-06-26 09:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KhuVuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_khu_vuc",
                    models.CharField(
                        help_text="Mã khu vực (A, B, C, D...)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "ten_khu_vuc",
                    models.CharField(help_text="Tên khu vực", max_length=100),
                ),
                (
                    "mo_ta",
                    models.TextField(blank=True, help_text="Mô tả chi tiết khu vực"),
                ),
                (
                    "kich_thuoc_hang",
                    models.IntegerField(
                        help_text="Số hàng trong khu vực",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "kich_thuoc_cot",
                    models.IntegerField(
                        help_text="Số cột trong khu vực",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "tai_trong_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tải trọng tối đa (kg)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "nhiet_do_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Nhiệt độ tối thiểu (°C)",
                        max_digits=5,
                    ),
                ),
                (
                    "nhiet_do_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        help_text="Nhiệt độ tối đa (°C)",
                        max_digits=5,
                    ),
                ),
                (
                    "do_am_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Độ ẩm tối thiểu (%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "do_am_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Độ ẩm tối đa (%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Hoạt_động", "Hoạt động"),
                            ("Bảo_trì", "Bảo trì"),
                            ("Ngừng", "Ngừng hoạt động"),
                        ],
                        default="Hoạt_động",
                        help_text="Trạng thái khu vực",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Khu vực",
                "verbose_name_plural": "Khu vực",
                "db_table": "khu_vuc",
                "ordering": ["ma_khu_vuc"],
            },
        ),
        migrations.CreateModel(
            name="NhaCungCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_nha_cung_cap", models.CharField(max_length=20, unique=True)),
                ("ten_nha_cung_cap", models.CharField(max_length=200)),
                ("dia_chi", models.TextField(blank=True, null=True)),
                (
                    "so_dien_thoai",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nguoi_lien_he",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "so_dien_thoai_lien_he",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email_lien_he",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ma_so_thue", models.CharField(blank=True, max_length=50, null=True)),
                ("loai_hang_cung_cap", models.JSONField(blank=True, null=True)),
                (
                    "xep_hang",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        default="B",
                        max_length=9,
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Hoạt_động", "Hoạt động"),
                            ("Tạm_dừng", "Tạm dừng"),
                            ("Ngừng", "Ngừng"),
                        ],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nhà cung cấp",
                "verbose_name_plural": "Nhà cung cấp",
                "db_table": "nha_cung_cap",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NhomHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_nhom", models.CharField(max_length=20, unique=True)),
                ("ten_nhom", models.CharField(max_length=100)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("mau_sac", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "yeu_cau_nhiet_do_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "yeu_cau_nhiet_do_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "yeu_cau_do_am_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "yeu_cau_do_am_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tranh_anh_sang",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "tranh_rung_dong",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hang_de_vo",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "hang_nguy_hiem",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("thu_tu_hien_thi", models.IntegerField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("Hoạt_động", "Hoạt động"), ("Ngừng", "Ngừng")],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Nhóm hàng",
                "verbose_name_plural": "Nhóm hàng",
                "db_table": "nhom_hang",
                "ordering": ["ma_nhom"],
            },
        ),
        migrations.CreateModel(
            name="Pallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_pallet",
                    models.CharField(
                        help_text="Mã pallet tự động (P-YYYY-XXX)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "so_thung_ban_dau",
                    models.IntegerField(
                        help_text="Số thùng ban đầu khi nhập",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "so_thung_con_lai",
                    models.IntegerField(
                        help_text="Số thùng còn lại hiện tại",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("ngay_san_xuat", models.DateField(help_text="Ngày sản xuất hàng hóa")),
                ("han_su_dung", models.DateField(help_text="Hạn sử dụng")),
                (
                    "ngay_nhap_kho",
                    models.DateTimeField(auto_now_add=True, help_text="Ngày nhập kho"),
                ),
                (
                    "ngay_kiem_tra_cl",
                    models.DateField(help_text="Ngày kiểm tra chất lượng tiếp theo"),
                ),
                (
                    "trong_luong_thung",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Trọng lượng mỗi thùng (kg)",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "chieu_cao",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Chiều cao pallet (cm)",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "chieu_dai",
                    models.DecimalField(
                        decimal_places=2,
                        default=120,
                        help_text="Chiều dài pallet (cm)",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "chieu_rong",
                    models.DecimalField(
                        decimal_places=2,
                        default=80,
                        help_text="Chiều rộng pallet (cm)",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Mới", "Mới nhập"),
                            ("Đã_mở", "Đã mở (xuất một phần)"),
                            ("Trống", "Đã xuất hết"),
                            ("Hỏng", "Hàng hỏng"),
                            ("Cách_ly", "Cách ly kiểm tra"),
                            ("Chờ_xuất", "Chờ xuất hàng"),
                        ],
                        default="Mới",
                        help_text="Trạng thái pallet",
                        max_length=20,
                    ),
                ),
                (
                    "lo_san_xuat",
                    models.CharField(
                        blank=True, help_text="Lô sản xuất", max_length=50
                    ),
                ),
                (
                    "so_phieu_nhap",
                    models.CharField(
                        blank=True, help_text="Số phiếu nhập kho", max_length=50
                    ),
                ),
                (
                    "nhiet_do_bao_quan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nhiệt độ bảo quản yêu cầu (°C)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "do_am_bao_quan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Độ ẩm bảo quản yêu cầu (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="QR Code của pallet",
                        null=True,
                        upload_to="qr_codes/pallets/",
                    ),
                ),
                (
                    "nguoi_tao",
                    models.CharField(help_text="Người tạo pallet", max_length=50),
                ),
                (
                    "ghi_chu",
                    models.TextField(blank=True, help_text="Ghi chú về pallet"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nha_cung_cap",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nhà cung cấp",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.nhacungcap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pallet",
                "verbose_name_plural": "Pallets",
                "db_table": "pallets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ViTriKho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_vi_tri",
                    models.CharField(
                        help_text="Mã vị trí (A1, A2, B1, B2...)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "hang",
                    models.CharField(help_text="Hàng (A, B, C, D, E...)", max_length=1),
                ),
                (
                    "cot",
                    models.IntegerField(
                        help_text="Cột (1, 2, 3, 4, 5...)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "loai_vi_tri",
                    models.CharField(
                        choices=[
                            ("Pallet", "Pallet"),
                            ("Carton", "Carton"),
                            ("Bulk", "Bulk"),
                        ],
                        default="Pallet",
                        help_text="Loại vị trí lưu trữ",
                        max_length=10,
                    ),
                ),
                (
                    "tai_trong_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tải trọng tối đa (kg)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "chieu_cao_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Chiều cao tối đa (cm)",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Trống", "Trống"),
                            ("Có_hàng", "Có hàng"),
                            ("Bảo_trì", "Bảo trì"),
                            ("Hỏng", "Hỏng"),
                        ],
                        default="Trống",
                        help_text="Trạng thái vị trí",
                        max_length=20,
                    ),
                ),
                (
                    "uu_tien_fifo",
                    models.BooleanField(
                        default=True, help_text="Ưu tiên FIFO (First In First Out)"
                    ),
                ),
                (
                    "gan_cua_ra",
                    models.BooleanField(
                        default=False, help_text="Gần cửa ra (xuất hàng nhanh)"
                    ),
                ),
                (
                    "vi_tri_cach_ly",
                    models.BooleanField(
                        default=False, help_text="Vị trí cách ly (hàng đặc biệt)"
                    ),
                ),
                (
                    "ghi_chu",
                    models.TextField(blank=True, help_text="Ghi chú về vị trí"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "khu_vuc",
                    models.ForeignKey(
                        help_text="Khu vực chứa vị trí này",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vi_tri_set",
                        to="warehouse.khuvuc",
                    ),
                ),
                (
                    "pallet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pallet đang được lưu trữ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vi_tri_set",
                        to="warehouse.pallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vị trí kho",
                "verbose_name_plural": "Vị trí kho",
                "db_table": "vi_tri_kho",
                "ordering": ["khu_vuc__ma_khu_vuc", "hang", "cot"],
            },
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_san_pham", models.CharField(max_length=50, unique=True)),
                ("ten_san_pham", models.CharField(max_length=100)),
                (
                    "thuong_hieu",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dung_tich",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("don_vi_tinh", models.CharField(blank=True, max_length=20, null=True)),
                ("so_luong_per_thung", models.IntegerField(blank=True, null=True)),
                ("ma_vach", models.CharField(blank=True, max_length=100, null=True)),
                ("han_su_dung_mac_dinh", models.IntegerField(blank=True, null=True)),
                ("chu_ky_kiem_tra_cl", models.IntegerField(blank=True, null=True)),
                ("hinh_anh", models.CharField(blank=True, max_length=255, null=True)),
                ("mo_ta", models.TextField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("Hoạt_động", "Hoạt động"), ("Ngừng", "Ngừng")],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nha_cung_cap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.nhacungcap",
                    ),
                ),
                (
                    "nhom_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.nhomhang",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Sản phẩm",
                "db_table": "san_pham",
                "ordering": ["ma_san_pham"],
            },
        ),
        migrations.AddField(
            model_name="pallet",
            name="san_pham",
            field=models.ForeignKey(
                help_text="Sản phẩm trong pallet",
                on_delete=django.db.models.deletion.PROTECT,
                to="warehouse.sanpham",
            ),
        ),
        migrations.AddField(
            model_name="pallet",
            name="vi_tri_kho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pallet_set",
                to="warehouse.vitrikho",
            ),
        ),
        migrations.AddIndex(
            model_name="khuvuc",
            index=models.Index(
                fields=["ma_khu_vuc"], name="khu_vuc_ma_khu__5ff2b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="khuvuc",
            index=models.Index(
                fields=["trang_thai"], name="khu_vuc_trang_t_654086_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vitrikho",
            index=models.Index(
                fields=["ma_vi_tri"], name="vi_tri_kho_ma_vi_t_3d2f1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vitrikho",
            index=models.Index(
                fields=["khu_vuc", "trang_thai"], name="vi_tri_kho_khu_vuc_6aaf11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vitrikho",
            index=models.Index(
                fields=["hang", "cot"], name="vi_tri_kho_hang_c5a7cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vitrikho",
            index=models.Index(
                fields=["trang_thai"], name="vi_tri_kho_trang_t_b2989f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vitrikho",
            index=models.Index(
                fields=["uu_tien_fifo"], name="vi_tri_kho_uu_tien_bfe8aa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vitrikho",
            constraint=models.UniqueConstraint(
                fields=("khu_vuc", "hang", "cot"), name="unique_khu_vuc_hang_cot"
            ),
        ),
        migrations.AddIndex(
            model_name="pallet",
            index=models.Index(fields=["ma_pallet"], name="pallets_ma_pall_eecc21_idx"),
        ),
        migrations.AddIndex(
            model_name="pallet",
            index=models.Index(
                fields=["san_pham", "trang_thai"], name="pallets_san_pha_5f33ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pallet",
            index=models.Index(
                fields=["han_su_dung"], name="pallets_han_su__56531b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pallet",
            index=models.Index(
                fields=["ngay_kiem_tra_cl"], name="pallets_ngay_ki_d2656a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pallet",
            index=models.Index(
                fields=["trang_thai"], name="pallets_trang_t_4fec1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pallet",
            index=models.Index(
                fields=["vi_tri_kho"], name="pallets_vi_tri__e95d53_idx"
            ),
        ),
    ]
