# Generated by Django 4.2.20 on 2025-06-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nhacungcap",
            name="dia_chi",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="email",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="email_lien_he",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="ghi_chu",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="loai_hang_cung_cap",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="ma_so_thue",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="nguoi_lien_he",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="so_dien_thoai",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="so_dien_thoai_lien_he",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("Hoạt_động", "Hoạt động"),
                    ("Tạm_dừng", "Tạm dừng"),
                    ("Ngừng", "Ngừng"),
                ],
                default="Hoạt_động",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="xep_hang",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                default="B",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="hang_de_vo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="hang_nguy_hiem",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="icon",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="mau_sac",
            field=models.CharField(default="#007bff", max_length=7),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="mo_ta",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="thu_tu_hien_thi",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="trang_thai",
            field=models.CharField(
                choices=[("Hoạt_động", "Hoạt động"), ("Ngừng", "Ngừng")],
                default="Hoạt_động",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="tranh_anh_sang",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="tranh_rung_dong",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="chu_ky_kiem_tra_cl",
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="don_vi_tinh",
            field=models.CharField(default="thùng", max_length=20),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="han_su_dung_mac_dinh",
            field=models.IntegerField(default=365, null=True),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="hinh_anh",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="ma_vach",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="mo_ta",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="so_luong_per_thung",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="thuong_hieu",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="trang_thai",
            field=models.CharField(
                choices=[("Hoạt_động", "Hoạt động"), ("Ngừng", "Ngừng")],
                default="Hoạt_động",
                max_length=20,
            ),
        ),
    ]
