# Generated by Django 4.2.20 on 2025-06-29 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_alter_nhacungcap_dia_chi_alter_nhacungcap_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nhacungcap",
            name="email",
            field=models.EmailField(
                default="",
                error_messages={"invalid": "Email không hợp lệ!"},
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="email_lien_he",
            field=models.EmailField(
                default="",
                error_messages={"invalid": "Email không hợp lệ!"},
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="ghi_chu",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="yeu_cau_do_am_max",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="yeu_cau_do_am_min",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="yeu_cau_nhiet_do_max",
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="yeu_cau_nhiet_do_min",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
