# Generated by Django 4.2.20 on 2025-07-01 08:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_alter_nhacungcap_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="khuvuc",
            name="do_am_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100,
                help_text="Độ ẩm tối đa (%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="khuvuc",
            name="do_am_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Độ ẩm tối thiểu (%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="khuvuc",
            name="nhiet_do_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=40,
                help_text="Nhiệt độ tối đa (°C)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="khuvuc",
            name="nhiet_do_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Nhiệt độ tối thiểu (°C)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="khuvuc",
            name="tai_trong_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Tải trọng tối đa (kg)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="dia_chi",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                error_messages={"invalid": "Email không hợp lệ!"},
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="email_lien_he",
            field=models.EmailField(
                blank=True,
                default="",
                error_messages={"invalid": "Email không hợp lệ!"},
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="loai_hang_cung_cap",
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="ma_so_thue",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="nguoi_lien_he",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="so_dien_thoai",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="so_dien_thoai_lien_he",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="icon",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="mau_sac",
            field=models.CharField(blank=True, default="#007bff", max_length=7),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="mo_ta",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="thu_tu_hien_thi",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="yeu_cau_do_am_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="yeu_cau_do_am_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="yeu_cau_nhiet_do_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=30, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="nhomhang",
            name="yeu_cau_nhiet_do_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="chieu_cao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Chiều cao pallet (cm)",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="chieu_dai",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=120,
                help_text="Chiều dài pallet (cm)",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="chieu_rong",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=80,
                help_text="Chiều rộng pallet (cm)",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="han_su_dung",
            field=models.DateField(blank=True, help_text="Hạn sử dụng"),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="ma_pallet",
            field=models.CharField(
                blank=True,
                help_text="Mã pallet tự động (P-YYYY-XXX)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="ngay_kiem_tra_cl",
            field=models.DateField(
                blank=True, help_text="Ngày kiểm tra chất lượng tiếp theo"
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="ngay_san_xuat",
            field=models.DateField(blank=True, help_text="Ngày sản xuất hàng hóa"),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="nguoi_tao",
            field=models.CharField(
                blank=True, help_text="Người tạo pallet", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="nha_cung_cap",
            field=models.ForeignKey(
                help_text="Nhà cung cấp",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.nhacungcap",
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="trong_luong_thung",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Trọng lượng mỗi thùng (kg)",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="vi_tri_kho",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pallet_set",
                to="warehouse.vitrikho",
            ),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="chu_ky_kiem_tra_cl",
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="don_vi_tinh",
            field=models.CharField(blank=True, default="thùng", max_length=20),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="han_su_dung_mac_dinh",
            field=models.IntegerField(blank=True, default=365, null=True),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="hinh_anh",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="ma_vach",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="mo_ta",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="so_luong_per_thung",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="thuong_hieu",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="vitrikho",
            name="chieu_cao_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Chiều cao tối đa (cm)",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="vitrikho",
            name="loai_vi_tri",
            field=models.CharField(
                blank=True,
                choices=[("Pallet", "Pallet"), ("Carton", "Carton"), ("Bulk", "Bulk")],
                default="Pallet",
                help_text="Loại vị trí lưu trữ",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vitrikho",
            name="tai_trong_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Tải trọng tối đa (kg)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="vitrikho",
            name="trang_thai",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Trống", "Trống"),
                    ("Có_hàng", "Có hàng"),
                    ("Bảo_trì", "Bảo trì"),
                    ("Hỏng", "Hỏng"),
                ],
                default="Trống",
                help_text="Trạng thái vị trí",
                max_length=20,
            ),
        ),
    ]
