# Generated by Django 4.2.20 on 2025-07-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_alter_khuvuc_do_am_max_alter_khuvuc_do_am_min_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pallet",
            name="nha_cung_cap",
            field=models.ForeignKey(
                blank=True,
                help_text="Nhà cung cấp",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouse.nhacungcap",
            ),
        ),
        migrations.AlterField(
            model_name="pallet",
            name="vi_tri_kho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pallet_set",
                to="warehouse.vitrikho",
            ),
        ),
    ]
