# Generated by Django 4.2.20 on 2025-06-26 09:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuaHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_cua_hang", models.CharField(max_length=20, unique=True)),
                ("ten_cua_hang", models.CharField(max_length=100)),
                (
                    "so_dien_thoai",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("dia_chi", models.CharField(max_length=100)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("Hoạt_động", "Hoạt động"), ("Tạm_dừng", "Tạm dừng")],
                        default="Hoạt_động",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cửa hàng",
                "verbose_name_plural": "Cửa hàng",
                "db_table": "cua_hang",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonXuat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_don", models.CharField(max_length=20, unique=True)),
                ("ngay_tao", models.DateField()),
                ("ngay_giao", models.DateField(blank=True, null=True)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Chờ_xuất", "Chờ xuất"),
                            ("Đang_xuất", "Đang xuất"),
                            ("Hoàn_thành", "Hoàn thành"),
                            ("Hủy", "Hủy"),
                        ],
                        default="Chờ_xuất",
                        max_length=10,
                    ),
                ),
                ("qr_code_data", models.TextField(blank=True, null=True)),
                ("da_in_qr", models.BooleanField(blank=True, default=False, null=True)),
                ("nguoi_tao", models.CharField(blank=True, max_length=50, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cua_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.cuahang"
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn xuất",
                "verbose_name_plural": "Đơn xuất",
                "db_table": "don_xuat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThuTuXuatHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thu_tu_mac_dinh", models.IntegerField()),
                ("thu_tu_tuy_chinh", models.IntegerField()),
                ("thoi_gian_uoc_tinh", models.IntegerField(default=0)),
                ("khoang_cach_uoc_tinh", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "don_xuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.donxuat"
                    ),
                ),
                (
                    "san_pham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.sanpham",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thứ tự xuất hàng",
                "verbose_name_plural": "Thứ tự xuất hàng",
                "db_table": "thu_tu_xuat_hang",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChiTietDon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_luong_can",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("pallet_assignments", models.JSONField(blank=True, null=True)),
                ("da_xuat_xong", models.BooleanField(default=False, null=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                (
                    "don_xuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.donxuat"
                    ),
                ),
                (
                    "san_pham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.sanpham",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết đơn",
                "verbose_name_plural": "Chi tiết đơn",
                "db_table": "chi_tiet_don",
            },
        ),
    ]
