# Generated by Django 4.2.20 on 2025-06-27 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_alter_nhacungcap_dia_chi_alter_nhacungcap_email_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LichSuXuatNhap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loai_giao_dich",
                    models.CharField(
                        choices=[
                            ("Nhập", "Nhập"),
                            ("Xuất", "Xuất"),
                            ("Di_chuyển", "Di chuyển"),
                            ("Điều_chỉnh", "Điều chỉnh"),
                        ],
                        default="Nhập",
                    ),
                ),
                ("so_luong", models.IntegerField()),
                (
                    "nguoi_thuc_hien",
                    models.CharField(blank=True, default="", null=True),
                ),
                ("ngay_thuc_hien", models.DateTimeField(auto_now_add=True)),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                (
                    "don_xuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.donxuat"
                    ),
                ),
                (
                    "pallets",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.pallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử xuất nhập",
                "verbose_name_plural": "Lịch sử xuất nhập",
                "db_table": "lich_su_xuat_nhap",
                "ordering": ["-ngay_thuc_hien"],
            },
        ),
    ]
