# Generated by Django 4.2.20 on 2025-06-27 02:40

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_lichsuxuatnhap"),
    ]

    operations = [
        migrations.AddField(
            model_name="chitietdon",
            name="so_luong_da_xuat",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="cuahang",
            name="khu_vuc",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="chitietdon",
            name="ghi_chu",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="chitietdon",
            name="pallet_assignments",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="cuahang",
            name="so_dien_thoai",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="cuahang",
            name="trang_thai",
            field=models.CharField(
                choices=[("Hoạt_động", "Hoạt động"), ("Tạm_dừng", "Tạm dừng")],
                default="Hoạt_động",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donxuat",
            name="da_in_qr",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="donxuat",
            name="ghi_chu",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="donxuat",
            name="ngay_tao",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="donxuat",
            name="nguoi_tao",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="donxuat",
            name="qr_code_data",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="donxuat",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("Chờ_xuất", "Chờ xuất"),
                    ("Đang_xuất", "Đang xuất"),
                    ("Hoàn_thành", "Hoàn thành"),
                    ("Hủy", "Hủy"),
                ],
                default="Chờ_xuất",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lichsuxuatnhap",
            name="ghi_chu",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="lichsuxuatnhap",
            name="loai_giao_dich",
            field=models.CharField(
                choices=[
                    ("Nhập", "Nhập"),
                    ("Xuất", "Xuất"),
                    ("Di_chuyển", "Di chuyển"),
                    ("Điều_chỉnh", "Điều chỉnh"),
                ],
                default="Nhập",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lichsuxuatnhap",
            name="nguoi_thuc_hien",
            field=models.CharField(default=""),
        ),
    ]
