# Generated by Django 4.2.20 on 2025-06-29 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_chitietdon_so_luong_da_xuat_cuahang_khu_vuc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitietdon",
            name="ghi_chu",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="chitietdon",
            name="so_luong_da_xuat",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="lichsuxuatnhap",
            name="ghi_chu",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="lichsuxuatnhap",
            name="so_luong",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="thutuxuathang",
            name="thu_tu_tuy_chinh",
            field=models.IntegerField(null=True),
        ),
    ]
