# Generated by Django 4.2.20 on 2025-07-01 08:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_chitietdon_ghi_chu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitietdon",
            name="da_xuat_xong",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="chitietdon",
            name="pallet_assignments",
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name="chitietdon",
            name="so_luong_can",
            field=models.IntegerField(
                blank=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="chitietdon",
            name="so_luong_da_xuat",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="cuahang",
            name="dia_chi",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="cuahang",
            name="khu_vuc",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="cuahang",
            name="so_dien_thoai",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="donxuat",
            name="ghi_chu",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="donxuat",
            name="ngay_tao",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="donxuat",
            name="nguoi_tao",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="donxuat",
            name="qr_code_data",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="lichsuxuatnhap",
            name="nguoi_thuc_hien",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="lichsuxuatnhap",
            name="so_luong",
            field=models.IntegerField(
                blank=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="thutuxuathang",
            name="khoang_cach_uoc_tinh",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="thutuxuathang",
            name="thoi_gian_uoc_tinh",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="thutuxuathang",
            name="thu_tu_mac_dinh",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="thutuxuathang",
            name="thu_tu_tuy_chinh",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
