# Generated by Django 4.2.20 on 2025-07-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_chitietdon_da_xuat_xong_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitietdon",
            name="pallet_assignments",
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
