# Generated by Django 4.2.20 on 2025-07-02 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_chitietdon_da_xuat_xong_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitietdon",
            name="pallet_assignments",
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name="lichsuxuatnhap",
            name="don_xuat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.donxuat",
            ),
        ),
    ]
