# Generated by Django 4.2.20 on 2025-06-26 09:24

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("warehouse", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("admin", "System Administrator"),
                            ("manager", "Warehouse Manager"),
                            ("supervisor", "Warehouse Supervisor"),
                            ("staff", "Warehouse Staff"),
                            ("viewer", "View Only User"),
                            ("delivery", "Delivery Staff"),
                            ("quality", "Quality Control Staff"),
                        ],
                        default="staff",
                        help_text="Loại tài khoản người dùng",
                        max_length=20,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Mã nhân viên",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Số điện thoại liên hệ",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Số điện thoại phải có định dạng: '+999999999'. Tối đa 15 chữ số.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Địa chỉ")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Ảnh đại diện",
                        null=True,
                        upload_to="avatars/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending Approval"),
                        ],
                        default="pending",
                        help_text="Trạng thái tài khoản",
                        max_length=20,
                    ),
                ),
                (
                    "is_active_session",
                    models.BooleanField(
                        default=False, help_text="Đang trong phiên làm việc"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, help_text="Thời gian hoạt động cuối"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Thời gian duyệt tài khoản", null=True
                    ),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(default=True, help_text="Bật thông báo"),
                ),
                (
                    "email_notification",
                    models.BooleanField(
                        default=True, help_text="Nhận thông báo qua email"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="vi", help_text="Ngôn ngữ giao diện", max_length=10
                    ),
                ),
                (
                    "timezone_user",
                    models.CharField(
                        default="Asia/Ho_Chi_Minh", help_text="Múi giờ", max_length=50
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(default=0, help_text="Số lần đăng nhập sai"),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, help_text="Khóa tài khoản đến", null=True
                    ),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Lần đổi mật khẩu cuối"
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False,
                        help_text="Bắt buộc đổi mật khẩu lần đăng nhập tiếp theo",
                    ),
                ),
                (
                    "total_login_count",
                    models.IntegerField(default=0, help_text="Tổng số lần đăng nhập"),
                ),
                (
                    "last_password_change",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Lần thay đổi mật khẩu cuối"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Người duyệt tài khoản",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Người tạo tài khoản này",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "warehouse_access",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Các khu vực kho được phép truy cập",
                        related_name="accessible_users",
                        to="warehouse.khuvuc",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Tên vai trò", max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="Mã vai trò (unique)", max_length=50, unique=True
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("admin", "System Administrator"),
                            ("manager", "Warehouse Manager"),
                            ("supervisor", "Warehouse Supervisor"),
                            ("staff", "Warehouse Staff"),
                            ("viewer", "View Only"),
                            ("delivery", "Delivery Staff"),
                            ("quality", "Quality Control"),
                            ("custom", "Custom Role"),
                        ],
                        default="custom",
                        help_text="Loại vai trò",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Mô tả chi tiết vai trò"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="active",
                        help_text="Trạng thái vai trò",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Vai trò có đang hoạt động"
                    ),
                ),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False, help_text="Vai trò hệ thống (không thể xóa)"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Độ ưu tiên (số càng cao càng ưu tiên)"
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        blank=True,
                        help_text="Số lượng user tối đa cho vai trò này",
                        null=True,
                    ),
                ),
                (
                    "auto_assign",
                    models.BooleanField(
                        default=False, help_text="Tự động gán cho user mới"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Thời gian tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Thời gian cập nhật cuối"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Dữ liệu bổ sung dạng JSON"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Người tạo vai trò",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Người cập nhật cuối",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="PermissionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("grant_permission", "Cấp quyền"),
                            ("revoke_permission", "Thu hồi quyền"),
                            ("assign_role", "Gán vai trò"),
                            ("remove_role", "Xóa vai trò"),
                            ("create_role", "Tạo vai trò"),
                            ("update_role", "Cập nhật vai trò"),
                            ("delete_role", "Xóa vai trò"),
                            ("login_attempt", "Thử đăng nhập"),
                            ("access_denied", "Từ chối truy cập"),
                            ("module_access", "Truy cập module"),
                            ("action_performed", "Thực hiện hành động"),
                        ],
                        help_text="Loại hành động",
                        max_length=30,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True, help_text="Module liên quan", max_length=30
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, help_text="Hành động cụ thể", max_length=20
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Hành động có thành công không"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Thông báo lỗi (nếu có)"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Địa chỉ IP", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User Agent")),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Dữ liệu request"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Dữ liệu response"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Thời gian thực hiện"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Ghi chú bổ sung")),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vai trò liên quan",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.role",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User bị tác động (nếu có)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_permission_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User thực hiện hành động",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Audit Log",
                "verbose_name_plural": "Permission Audit Logs",
                "db_table": "permission_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("nhap_hang", "Module 1: Nhập hàng"),
                            ("tao_don", "Module 2: Tạo đơn"),
                            ("xuat_hang", "Module 3: Xuất hàng"),
                            ("quan_ly_kho", "Module 4: Quản lý kho"),
                            ("kiem_tra_giao_hang", "Module 5: Kiểm tra giao hàng"),
                            ("admin_panel", "Admin Panel"),
                            ("reports", "Báo cáo & Thống kê"),
                            ("settings", "Cài đặt hệ thống"),
                            ("user_management", "Quản lý người dùng"),
                            ("role_management", "Quản lý vai trò"),
                            ("warehouse_config", "Cấu hình kho"),
                            ("system_logs", "Nhật ký hệ thống"),
                        ],
                        help_text="Module/Chức năng",
                        max_length=30,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Xem/Đọc"),
                            ("create", "Tạo mới"),
                            ("edit", "Chỉnh sửa"),
                            ("delete", "Xóa"),
                            ("export", "Xuất dữ liệu"),
                            ("import", "Nhập dữ liệu"),
                            ("print", "In ấn"),
                            ("approve", "Duyệt/Phê duyệt"),
                            ("reject", "Từ chối"),
                            ("assign", "Phân công"),
                            ("transfer", "Chuyển đổi"),
                            ("manage_users", "Quản lý người dùng"),
                            ("manage_roles", "Quản lý vai trò"),
                            ("system_config", "Cấu hình hệ thống"),
                            ("full_access", "Toàn quyền"),
                        ],
                        help_text="Hành động được phép",
                        max_length=20,
                    ),
                ),
                (
                    "is_granted",
                    models.BooleanField(
                        default=True, help_text="Quyền có được cấp hay không"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Điều kiện bổ sung (JSON format)",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Thời hạn hiệu lực quyền", null=True
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Thời gian cấp quyền"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Thời gian cập nhật cuối"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Lý do cấp/thu hồi quyền"),
                ),
                ("notes", models.TextField(blank=True, help_text="Ghi chú bổ sung")),
                (
                    "granted_by",
                    models.ForeignKey(
                        help_text="Người cấp quyền",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Vai trò được cấp quyền",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Permission",
                "verbose_name_plural": "Module Permissions",
                "db_table": "module_permissions",
                "ordering": ["role", "module", "action"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Vai trò có đang hoạt động cho user này"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Thời gian gán vai trò"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Thời hạn hiệu lực vai trò", null=True
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, help_text="Thời gian thu hồi vai trò", null=True
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Lý do gán/thu hồi vai trò"),
                ),
                ("notes", models.TextField(blank=True, help_text="Ghi chú bổ sung")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Người gán vai trò",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Người thu hồi vai trò",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Vai trò",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Người dùng",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "user_roles",
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_roles_user_id_4ec42c_idx",
                    ),
                    models.Index(
                        fields=["role", "is_active"],
                        name="user_roles_role_id_57352b_idx",
                    ),
                    models.Index(
                        fields=["assigned_at"], name="user_roles_assigne_f2447a_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="user_roles_expires_aafda2_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "role"),
                name="unique_active_user_role",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["role_type", "is_active"], name="roles_role_ty_00f0e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="roles_code_25c050_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["status"], name="roles_status_86510b_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["created_by"], name="roles_created_e7b3b3_idx"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique_role_code"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="permission__user_id_ed2b21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["action_type", "timestamp"],
                name="permission__action__4a1a9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["target_user", "timestamp"],
                name="permission__target__ceb496_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["module", "action"], name="permission__module_60c2e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["success"], name="permission__success_edae13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modulepermission",
            index=models.Index(
                fields=["role", "module"], name="module_perm_role_id_f8a6e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modulepermission",
            index=models.Index(
                fields=["module", "action"], name="module_perm_module_f01ed9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modulepermission",
            index=models.Index(
                fields=["is_granted"], name="module_perm_is_gran_db0a21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modulepermission",
            index=models.Index(
                fields=["expires_at"], name="module_perm_expires_c61698_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="modulepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "module", "action"), name="unique_role_module_action"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type", "status"], name="users_user_ty_cd71db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["employee_id"], name="users_employe_55e465_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "status"], name="users_is_acti_7a4a9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_by"], name="users_created_423079_idx"),
        ),
    ]
